### ISSUE TITLE
Branching

### ISSUE THREAD

**Issue by alkra** [VSasyan/TSIc#3]
(Pultôt pour @VSasyan )

La branche _logout_ est très loin en arrière, non fusionnée, et je ne retrouve pas le code de @MedAmiri de `logoutAction` sur la branche master. Est-ce normal ?

**Comment by VSasyan** [comment]
C'est normal : le logout est géré par Symfony, il ne faut déclarer l'action que pour créer la route.
Ensuite, Symfony intercepte le truc avant que l'action ait lieu.

On pourrait donc supprimer cette branche, mais pour le moment je préfère la conserver.
